version: '3'

services:
  db_ads:
    image: mysql:8.0
    container_name: db_ads
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./dbdata_ads:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - ads-network

  wordpress_ads:
    depends_on:
      - db_ads
    image: wordpress:5.8.2
    container_name: wordpress_ads
    restart: unless-stopped
    env_file: .env
    ports:
      - 9090:80
    environment:
      - WORDPRESS_DB_HOST=db_ads:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./uploads.ini.ads:/usr/local/etc/php/conf.d/uploads.ini
      - ./wordpress_ads:/var/www/html
    networks:
      - ads-network
  
networks:
  ads-network:
    driver: bridge  
